import type { GuidedTrialStep } from './tour-types';

/** Ordered stops for Chris's owner guided trial (spec 002). */
export const GUIDED_TRIAL_STEPS: GuidedTrialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Hangar Liquor Inventory',
    body: 'Quick trial run — nine short stops. Each one shows a real store tool and what it does for you. Tap Next to begin, or Skip anytime.',
  },
  {
    id: 'dashboard',
    route: '/',
    target: 'tour-dashboard',
    title: 'Home — your store at a glance',
    body: 'Low stock, total bottles, Top Movers, and holiday heads-ups live here. Home is on the bottom nav anytime — this stop opens it first so you see the store story.',
  },
  {
    id: 'scan',
    route: '/scan',
    target: 'tour-scan',
    title: 'Scan a bottle',
    body: 'On the floor, use the phone camera. On a laptop, type a UPC by hand — same result. Confirm the product and update stock in a couple of taps.',
    tryHint: 'Try typing a UPC and applying it (works without a camera).',
    tryTestId: 'guided-try-scan',
    requireTry: true,
  },
  {
    id: 'inventory',
    route: '/inventory',
    target: 'tour-inventory',
    title: 'Find & fix inventory',
    body: 'Search by name or UPC, filter by category, and edit quantities. Managers can also receive a shipment via CSV.',
  },
  {
    id: 'events',
    route: '/events',
    target: 'tour-events',
    title: 'Local events (Hay Days & hunting)',
    body: 'Wiley weekends bump demand — Hay Days, hunting opener, rodeos. Add an event so forecasts plan for beer, ice, and spirits, not a quiet Tuesday. National holidays lift automatically.',
    tryHint: 'Open the Hay Days example — see how a weekend fills in.',
    tryTestId: 'add-hay-days-example',
    requireTry: true,
  },
  {
    id: 'forecast',
    route: '/forecast',
    target: 'tour-forecast',
    title: 'Forecast — what you will need',
    body: 'Fourteen-day demand based on your patterns, local events, and holidays. Built for the store floor — no special setup required to read this screen.',
  },
  {
    id: 'suggestions',
    route: '/suggestions',
    target: 'tour-suggestions',
    title: 'Suggestions & holiday stocking',
    body: 'Act on the forecast: add stock or boost demand when something is running hot. Holiday stocking shows what to stage early for July 4, Thanksgiving, Christmas, and more.',
    tryHint: 'Peek at Holiday stocking, then try Add to Stock on a reorder row.',
    tryTestId: 'guided-try-add-stock',
    requireTry: true,
  },
  {
    id: 'profit',
    route: '/profit',
    target: 'tour-profit',
    title: 'Profit & Ask Hangar',
    body: 'Saved and Made — cash staying in your pocket — plus category mix. Ask Hangar plain questions about holidays, overstock, or beer cash. Amber banners mean demo estimates, not live register dollars yet.',
    tryHint: 'Ask what to stock for the next holiday — watch the reply appear.',
    tryTestId: 'ask-hangar-holiday',
    requireTry: true,
  },
  {
    id: 'more',
    route: '/more',
    target: 'tour-more',
    title: 'More — install & training',
    body: 'Put the app on a phone, reset demo training data, and when you are ready connect the register. You can restart this trial from here anytime.',
    tryHint: 'Confirm the install panel is here for phones.',
    tryTestId: 'install-app-panel',
  },
];
