#!/usr/bin/env tsx
/**
 * Pull Terraform outputs into .env.production for AWS-backed builds.
 *
 * Usage:
 *   npx tsx scripts/sync-aws-env.ts
 *   npx tsx scripts/sync-aws-env.ts --write-dotenv   # also copy → .env
 */
import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

function tfOutput(name: string): string {
  return execSync(`terraform -chdir=terraform output -raw ${name}`, {
    cwd: root,
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe'],
  }).trim();
}

function main() {
  const writeDotenv = process.argv.includes('--write-dotenv');

  const apiUrl = tfOutput('api_url');
  const poolId = tfOutput('cognito_user_pool_id');
  const clientId = tfOutput('cognito_client_id');
  const pwaUrl = tfOutput('frontend_url');

  const lines = [
    '# Auto-generated by scripts/sync-aws-env.ts — do not commit secrets',
    `VITE_API_URL=${apiUrl}`,
    `VITE_COGNITO_USER_POOL_ID=${poolId}`,
    `VITE_COGNITO_CLIENT_ID=${clientId}`,
    `VITE_PWA_URL=${pwaUrl}`,
    '# VITE_DEMO_AUTH is intentionally unset for production',
    '',
    '# Backend / CLI (bootstrap-owner, prep:aws)',
    'AWS_PROFILE=steve',
    `COGNITO_USER_POOL_ID=${poolId}`,
    'INVENTORY_TABLE=HangerInventory',
    'PRODUCTS_TABLE=HangerProducts',
    'SALES_HISTORY_TABLE=HangerSalesHistory',
    'LOCAL_EVENTS_TABLE=HangerLocalEvents',
    'STORE_ID=hanger',
    '',
  ];

  const outPath = path.join(root, '.env.production');
  fs.writeFileSync(outPath, lines.join('\n'));
  console.log(`✅ Wrote ${outPath}`);
  console.log(`   API:      ${apiUrl}`);
  console.log(`   PWA:      ${pwaUrl}`);
  console.log(`   Cognito:  ${poolId}`);

  if (writeDotenv) {
    fs.copyFileSync(outPath, path.join(root, '.env'));
    console.log('✅ Copied → .env');
  }
}

main();